In [34]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC


In [35]:

Health_dataset = pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\target\ml\Health_monitoring_systems\Health Monitor Dataset.csv")


In [36]:
Health_dataset.head()

Dehydration  Medicine Overdose  Acidious  Cold   Cough  Dehydration.1  \
0         True               True     False   True   True              1   
1        False               True      True  False   True              0   
2        False              False     False   True   True              0   
3        False              False     False  False   True              0   
4         True              False     False   True  False              1   

   Medicine Overdose.1  Acidious.1  Cold .1  Cough.1  Type  Temperature  \
0                    1           0        1        1     4           95   
1                    1           1        0        1     3           97   
2                    0           0        1        1     2          100   
3                    0           0        0        1     1           99   
4                    0           0        1        0     2          100   

   Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  Oxygen Saturation  PH  \
0          77     50     99     90                43               0.94   5   
1          56    101    105     50                46               0.97   4   
2          88    196     97     77                54               0.96   8   
3          62     62    120     63                15               1.00   8   
4         126     93     95     70                52               0.97   5   

  Causes Respiratory Imbalance  
0                      Chronic  
1                      Chronic  
2                       Severe  
3                         Mild  
4                       Severe

In [37]:
Health_dataset.shape

(4286, 20)

In [38]:
Health_dataset.describe()

Dehydration.1  Medicine Overdose.1   Acidious.1      Cold .1  \
count    4286.000000          4286.000000  4286.000000  4286.000000   
mean        0.502566             0.505600     0.486468     0.495100   
std         0.500052             0.500027     0.499875     0.500034   
min         0.000000             0.000000     0.000000     0.000000   
25%         0.000000             0.000000     0.000000     0.000000   
50%         1.000000             1.000000     0.000000     0.000000   
75%         1.000000             1.000000     1.000000     1.000000   
max         1.000000             1.000000     1.000000     1.000000   

           Cough.1         Type  Temperature   Heart Rate        Pulse  \
count  4286.000000  4286.000000  4286.000000  4286.000000  4286.000000   
mean      0.496267     2.486001   100.073728   115.765516   113.147224   
std       0.500044     1.133829     3.241098    42.873114    45.263131   
min       0.000000     0.000000    95.000000    50.000000    50.000000   
25%       0.000000     2.000000    98.000000    79.000000    68.000000   
50%       0.000000     2.000000    99.000000   106.000000   107.000000   
75%       1.000000     3.000000   103.000000   152.000000   153.000000   
max       1.000000     5.000000   106.000000   200.000000   200.000000   

             BPSYS        BPDIA  Respiratory Rate  Oxygen Saturation  \
count  4286.000000  4286.000000       4286.000000        4286.000000   
mean    101.355343    70.131591         29.772049           0.950154   
std       5.240401    16.065834         16.106836           0.030348   
min      90.000000    40.000000          6.000000           0.900000   
25%      98.000000    59.000000         15.000000           0.920000   
50%     101.000000    70.000000         28.000000           0.950000   
75%     104.000000    82.000000         44.000000           0.970000   
max     120.000000   100.000000         60.000000           1.000000   

                PH  
count  4286.000000  
mean      7.573495  
std       3.618710  
min       1.000000  
25%       5.000000  
50%       8.000000  
75%      10.000000  
max      14.000000

In [39]:
Health_dataset['Causes Respiratory Imbalance'].value_counts()

Causes Respiratory Imbalance
Chronic    2107
Severe     1371
Mild        648
Normal      160
Name: count, dtype: int64

In [40]:
print(Health_dataset.groupby('Causes Respiratory Imbalance').mean())

                              Dehydration  Medicine Overdose  Acidious  \
Causes Respiratory Imbalance                                             
Chronic                          0.688182           0.697200  0.682012   
Mild                             0.220679           0.203704  0.179012   
Normal                           0.000000           0.000000  0.000000   
Severe                           0.409190           0.412837  0.388038   

                                 Cold      Cough  Dehydration.1  \
Causes Respiratory Imbalance                                      
Chronic                       0.687233  0.693403       0.688182   
Mild                          0.192901  0.203704       0.220679   
Normal                        0.000000  0.000000       0.000000   
Severe                        0.400438  0.389497       0.409190   

                              Medicine Overdose.1  Acidious.1   Cold .1  \
Causes Respiratory Imbalance                                              
Ch

In [41]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder


print("Original column names:", Health_dataset.columns.tolist())


le = LabelEncoder()


Health_dataset.rename(columns=lambda x: x.strip(), inplace=True)


for column in Health_dataset.columns:
    if column in Health_dataset.columns[Health_dataset.columns.duplicated()]:
        Health_dataset.rename(columns={column: f"{column}_dup"}, inplace=True)


print("Updated column names:", Health_dataset.columns.tolist())


duplicates_to_drop = [
    'Cold_dup',
    'Cough_dup',
    'Dehydration_dup',
    'Medicine Overdose_dup',
    'Acidious_dup',
    'Dehydration.1',
    'Medicine Overdose.1',
    'Acidious.1'
]


Health_dataset.drop(columns=[col for col in duplicates_to_drop if col in Health_dataset.columns], inplace=True, errors='ignore')

if 'Cold' in Health_dataset.columns:
    Health_dataset['Cold'] = le.fit_transform(Health_dataset['Cold'])
if 'Cough' in Health_dataset.columns:
    Health_dataset['Cough'] = le.fit_transform(Health_dataset['Cough'])
if 'Dehydration' in Health_dataset.columns:
    Health_dataset['Dehydration'] = le.fit_transform(Health_dataset['Dehydration'])
if 'Medicine Overdose' in Health_dataset.columns:
    Health_dataset['Medicine Overdose'] = le.fit_transform(Health_dataset['Medicine Overdose'])
if 'Acidious' in Health_dataset.columns:
    Health_dataset['Acidious'] = le.fit_transform(Health_dataset['Acidious'])

Health_dataset.head()



Original column names: ['Dehydration', 'Medicine Overdose', 'Acidious', 'Cold ', 'Cough', 'Dehydration.1', 'Medicine Overdose.1', 'Acidious.1', 'Cold .1', 'Cough.1', 'Type', 'Temperature', 'Heart Rate', 'Pulse', 'BPSYS', 'BPDIA', 'Respiratory Rate', 'Oxygen Saturation', 'PH', 'Causes Respiratory Imbalance']
Updated column names: ['Dehydration', 'Medicine Overdose', 'Acidious', 'Cold', 'Cough', 'Dehydration.1', 'Medicine Overdose.1', 'Acidious.1', 'Cold .1', 'Cough.1', 'Type', 'Temperature', 'Heart Rate', 'Pulse', 'BPSYS', 'BPDIA', 'Respiratory Rate', 'Oxygen Saturation', 'PH', 'Causes Respiratory Imbalance']


Dehydration  Medicine Overdose  Acidious  Cold  Cough  Cold .1  Cough.1  \
0            1                  1         0     1      1        1        1   
1            0                  1         1     0      1        0        1   
2            0                  0         0     1      1        1        1   
3            0                  0         0     0      1        0        1   
4            1                  0         0     1      0        1        0   

   Type  Temperature  Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  \
0     4           95          77     50     99     90                43   
1     3           97          56    101    105     50                46   
2     2          100          88    196     97     77                54   
3     1           99          62     62    120     63                15   
4     2          100         126     93     95     70                52   

   Oxygen Saturation  PH Causes Respiratory Imbalance  
0               0.94   5                      Chronic  
1               0.97   4                      Chronic  
2               0.96   8                       Severe  
3               1.00   8                         Mild  
4               0.97   5                       Severe

In [42]:
# Define the mapping for the 'Causes Respiratory Imbalance' column
respiratory_imbalance_mapping = {
    'Normal': 0,
    'Mild': 1,
    'Severe': 2,
    'Chronic': 3
}

# Replace the values using the defined mapping
Health_dataset['Causes Respiratory Imbalance'] = Health_dataset['Causes Respiratory Imbalance'].replace(respiratory_imbalance_mapping)

# Display the first few rows to verify changes
print(Health_dataset[['Causes Respiratory Imbalance']].head())

   Causes Respiratory Imbalance
0                             3
1                             3
2                             2
3                             1
4                             2


In [43]:
X=Health_dataset.drop(columns='Causes Respiratory Imbalance',axis=1)
Y=Health_dataset['Causes Respiratory Imbalance']

In [44]:
X.head()

Dehydration  Medicine Overdose  Acidious  Cold  Cough  Cold .1  Cough.1  \
0            1                  1         0     1      1        1        1   
1            0                  1         1     0      1        0        1   
2            0                  0         0     1      1        1        1   
3            0                  0         0     0      1        0        1   
4            1                  0         0     1      0        1        0   

   Type  Temperature  Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  \
0     4           95          77     50     99     90                43   
1     3           97          56    101    105     50                46   
2     2          100          88    196     97     77                54   
3     1           99          62     62    120     63                15   
4     2          100         126     93     95     70                52   

   Oxygen Saturation  PH  
0               0.94   5  
1               0.97   4  
2               0.96   8  
3               1.00   8  
4               0.97   5

In [45]:
Y.head()

0    3
1    3
2    2
3    1
4    2
Name: Causes Respiratory Imbalance, dtype: int64

In [46]:
scaler = StandardScaler()

In [47]:
scaler.fit(X)

StandardScaler()

In [48]:
print(X)
print(Y)

      Dehydration  Medicine Overdose  Acidious  Cold  Cough  Cold .1  Cough.1  \
0               1                  1         0     1      1        1        1   
1               0                  1         1     0      1        0        1   
2               0                  0         0     1      1        1        1   
3               0                  0         0     0      1        0        1   
4               1                  0         0     1      0        1        0   
...           ...                ...       ...   ...    ...      ...      ...   
4281            1                  0         1     0      0        0        0   
4282            1                  0         0     0      1        0        1   
4283            1                  1         0     0      0        0        0   
4284            0                  0         1     1      0        1        0   
4285            0                  1         1     0      1        0        1   

      Type  Temperature  He

In [49]:
X_train,X_test,Y_train,Y_test= train_test_split(X,Y,test_size=0.9, stratify=Y, random_state=42)

In [50]:
print(X.shape,X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(4286, 16) (428, 16) (3858, 16) (428,) (3858,)


In [51]:
X_train.head()

Dehydration  Medicine Overdose  Acidious  Cold  Cough  Cold .1  Cough.1  \
3671            1                  1         0     1      1        1        1   
1086            1                  0         1     1      1        1        1   
329             1                  1         0     0      1        0        1   
896             1                  1         0     1      0        1        0   
190             0                  1         1     1      0        1        0   

      Type  Temperature  Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  \
3671     4           98         140    132    103     63                11   
1086     4          102          70     79     97     47                44   
329      3           96         186    191    104     59                55   
896      3           98          91    191    101     63                10   
190      3          103         191    162    105     68                38   

      Oxygen Saturation  PH  
3671               0.97  11  
1086               0.91  11  
329                0.96   9  
896                0.93  14  
190                0.92  11

In [52]:
Y_train.head()

3671    3
1086    3
329     3
896     3
190     3
Name: Causes Respiratory Imbalance, dtype: int64

In [53]:
X_test.head()

Dehydration  Medicine Overdose  Acidious  Cold  Cough  Cold .1  Cough.1  \
8               0                  0         0     0      0        0        0   
2872            1                  0         1     1      1        1        1   
3479            1                  1         1     1      1        1        1   
2685            0                  1         0     0      1        0        1   
1809            1                  0         0     1      0        1        0   

      Type  Temperature  Heart Rate  Pulse  BPSYS  BPDIA  Respiratory Rate  \
8        0           99          92     60     94     75                16   
2872     4          103         165     70    106     45                39   
3479     5          104         139    159    105     88                50   
2685     2          102         196    182    104     56                10   
1809     2          102          92     81    103     49                10   

      Oxygen Saturation  PH  
8                  1.00   8  
2872               0.97   6  
3479               0.93   8  
2685               0.97   3  
1809               0.91   4

In [54]:
Y_test.head()

8       0
2872    3
3479    3
2685    2
1809    2
Name: Causes Respiratory Imbalance, dtype: int64

In [55]:
classifier=svm.SVC(kernel='linear')

In [56]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [57]:
X_train_prediction=classifier.predict(X_train)
training_dataset_accuracy= accuracy_score(X_train_prediction,Y_train)

In [58]:
print('Accuracy for training dataset achived: ',training_dataset_accuracy*100)

Accuracy for training dataset achived:  100.0


In [59]:
X_test_prediction=classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction,Y_test)

In [60]:
print('Accuracy for test dataset achived: ',test_data_accuracy*100)

Accuracy for test dataset achived:  98.7817522032141


In [61]:
input_data=(0,1,1,1,0,1,0,3,103,82,60,106,95,27,0.94,13)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = classifier.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
    print('Normal')
elif(prediction[0]==1):
  print('Mild')
elif(prediction[0]==2):
  print('Severe')
elif(prediction[0]==3):
  print('Chronic')

[3]
Chronic


c:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [62]:
from sklearn.metrics import confusion_matrix

# Predict on the test data
X_test_prediction = classifier.predict(X_test)

# Generate the confusion matrix
conf_matrix = confusion_matrix(Y_test, X_test_prediction)
print("Confusion Matrix:\n", conf_matrix)



Confusion Matrix:
 [[ 144    0    0    0]
 [   2  575    6    0]
 [   0   39 1195    0]
 [   0    0    0 1897]]


In [63]:
from sklearn.metrics import classification_report

# Print precision, recall, f1-score for each class
print("Classification Report:\n", classification_report(Y_test, X_test_prediction))


Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      0.99       144
           1       0.94      0.99      0.96       583
           2       1.00      0.97      0.98      1234
           3       1.00      1.00      1.00      1897

    accuracy                           0.99      3858
   macro avg       0.98      0.99      0.98      3858
weighted avg       0.99      0.99      0.99      3858



In [64]:
from sklearn.metrics import matthews_corrcoef

mcc = matthews_corrcoef(Y_test, X_test_prediction)
print("Matthews Correlation Coefficient: {:.2f}".format(mcc))


Matthews Correlation Coefficient: 0.98


In [65]:
from sklearn.metrics import balanced_accuracy_score

balanced_acc = balanced_accuracy_score(Y_test, X_test_prediction)
print("Balanced Accuracy: {:.2f}".format(balanced_acc))


Balanced Accuracy: 0.99


In [66]:
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation
cv_scores = cross_val_score(classifier, X, Y, cv=5)

# Print the average accuracy
print("Average cross-validation accuracy: {:.2f}%".format(cv_scores.mean() * 100))


Average cross-validation accuracy: 100.00%


In [67]:
from sklearn.svm import SVC

# Add regularization (C=1.0) to reduce overfitting
classifier = SVC(kernel='linear', C=1.0, class_weight='balanced', probability=True)


In [68]:
from sklearn.model_selection import cross_val_score

# Perform 5-fold cross-validation
cv_scores = cross_val_score(classifier, X, Y, cv=5)

# Print the average accuracy
print("Average cross-validation accuracy: {:.2f}%".format(cv_scores.mean() * 100))

Average cross-validation accuracy: 100.00%
